### ISSUE TITLE
The site I mentioned doesn't work

### ISSUE THREAD

**Issue by idkaname1** [3kh0/3kh0.github.io-replit#20]
I deleted all the cookies and now it is just this, this is the site I used :
https://3kh0.github.io/projects 
![Screenshot 2023-03-03 19 30 06](https://user-images.githubusercontent.com/125160132/222868355-8ecf294e-1b62-4625-b093-e8d46c279566.png)

**Comment by Rahib777-7** [comment]
> I deleted all the cookies and now it is just this, this is the site I used :
> https://3kh0.github.io/projects
> ![Screenshot 2023-03-03 19 30 06](https://user-images.githubusercontent.com/125160132/222868355-8ecf294e-1b62-4625-b093-e8d46c279566.png)

3kh0's main site is down

**Comment by Rahib777-7** [comment]
use the replit version

**Comment by idkaname1** [comment]
whenever i try to play in the replit it does this
Stats for nerds
Please make a issue about this happening on the [Github issue tracker](https://github.com/3kh0/3kh0.github.io/issues) Requested URL: https://3kh0.github.io/3kh0.github.io-replit/files/1v1lol/index.html
Referrer: https://3kh0.github.io/3kh0.github.io-replit/projects.html
Title: Error | 3kh0
Screen height: 853px
Screen width: 1517px
Window height: 750px
Window width: 1517px
Cookies: true
User agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
OS platform: Linux x86_64
Online: true
Error code: 404
© 3kh0 2023

**Comment by Rahib777-7** [comment]
> whenever i try to play in the replit it does this
> Stats for nerds
> Please make a issue about this happening on the [Github issue tracker](https://github.com/3kh0/3kh0.github.io/issues) Requested URL: https://3kh0.github.io/3kh0.github.io-replit/files/1v1lol/index.html
> Referrer: https://3kh0.github.io/3kh0.github.io-replit/projects.html
> Title: Error | 3kh0
> Screen height: 853px
> Screen width: 1517px
> Window height: 750px
> Window width: 1517px
> Cookies: true
> User agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
> OS platform: Linux x86_64
> Online: true
> Error code: 404
> © 3kh0 1988

use a replit link instead of a github link

**Comment by idkaname1** [comment]
but i can't play minecraft

**Comment by 3kh0** [comment]
just contribute to the existing issue
